server:
  port: 11003
  undertow:
    io-threads: 2
    worker-threads: 20
    buffer-size: 1024

spring:
  profiles:
    active: 
    - ${project.environment}

  ### 项目基本信息
  application:
    name: "${server_name}"

  ### http配置
  http:
    encoding:
      charset: UTF-8
      force: true

  ### jackson配置
  jackson:
    serialization:
      write_dates_as_timestamps: false
      fail_on_empty_beans: false
    deserialization:
      fail_on_unknown_properties: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  mvc:
    throw-exception-if-no-handler-found: true

  output:
    ansi:
      enabled: always

management:
  info.git.mode: full
  security:
    enabled: false
  context-path: /_monitor

eureka:
  instance:
    perferIpAddress: true
  server:
    enable-self-preservation: true

---
spring:
  profiles: dev

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: test

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: pre

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: product

eureka:
  client:
    service-url:
      defaultZone: http://peer1.eureka:11003/eureka/,http://peer2.eureka:11003/eureka/,http://peer3.eureka:11003/eureka/